---
- name: Setup Icinga 2 master and create CA
  shell: "{{ icinga2_binary }} node setup --master --cn {{ icinga2_nodename }}"
  args:
    creates: "/var/lib/icinga2/ca/ca.crt"
  notify: Test config before restart icinga 2
  when: inventory_hostname == icinga2_ca_host
  tags:
    - install
    - config

- name: Manage icinga2 constants.conf
  template:
    src: constants.conf.j2
    dest: /etc/icinga2/constants.conf
    owner: "{{icinga2_user[ansible_os_family]}}"
    group: "{{ icinga2_group[ansible_os_family] }}"
    mode: 0640
  notify: Test config before restart icinga 2

- name: Manage icinga2 zones.conf
  template:
    src: zones.conf.j2
    dest: /etc/icinga2/zones.conf
    owner: "{{icinga2_user[ansible_os_family]}}"
    group: "{{ icinga2_group[ansible_os_family] }}"
    mode: 0640
  notify: Test config before restart icinga 2
  tags:
    - zones

- name: restart icinga after change
  meta: flush_handlers
  tags:
    - install
    - config

- name: Manage Certificates
  include_tasks: "pki.yml"
  when: inventory_hostname != icinga2_ca_host
  tags:
    - install
    - update

